### PR TITLE
Create example YAML

### LINKED ISSUE #6: [Feature Request] Add Example
Instead of just the example:

```yml
sensor:
  platform: faastatus
  id: BOS
```

Include a full example file of a configuration.yml file to see it being used in a real-world scenario. 

### Validation for Feature Request

If you install the add-on and try to edit the configuration.yml file too early, you see the following error:

`Platform error sensor.faastatus - Integration 'faastatus' not found`

### Example Idea For Use

By showing the warning in the actual configuraiton example, it will remediate any potential error:

Demo based on the out-of-box configuration.yml

```yml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

# Important, be sure to restart the Home Assistant before adding this 
# FAA Status
sensor:
 platform: faastatus
  id: BOS

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

### PR DESCRIPTION
**Pull request by ntilley905**
This is a pull request to add an example YAML. Closes #6

### CODE REVIEW

**Comment by ntilley905** [comment]
@LanceMcCarthy what do you think of this? Sorry for the delay in getting it done!

**Comment by LanceMcCarthy** [comment]
Looks great! Thanks.

**Comment by LanceMcCarthy** [comment]
Just wanted to follow now that I've had a real chance to dig in and start setting up card configuration and automations. Well done!

**Comment by ntilley905** [comment]
Glad it helps! Let me know if you see more room for improvement.

**Pull request merged**
